name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      # 3. Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Build web
      - name: Build web
        run: flutter build web --release

      # 5. Deploy to GitHub Pages repo
      - name: Deploy to GitHub Pages repo
        run: |
          cd build/web

          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git branch -M main

          git add .

          git commit -m "Deploy $(date)" || echo "No changes to commit"

          git remote add origin https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/muhamaadessam/muhamaadessam.github.io.git

          git push -f origin main